apiVersion: v1
kind: Service
metadata: 
  name: angular-service
spec:
  selector:
    app: angular
  type: LoadBalancer
  ports:
    - protocol: 'TCP'
      port: 2000
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
        - name: container-angular
          image: rockstban/angular-frontend:1.0.0